version: '3.9'
services:
  app:
    container_name: flask-app
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    ports:
      - '8007:8007'
    volumes:
      - .:/var/www/html
    networks:
      - flask
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: flask-db
    restart: always
    ports:
      - "33073:3306"
    environment:
      MYSQL_HOST: flask-db
      MYSQL_DATABASE: flask
      MYSQL_USER: admin
      MYSQL_ROOT: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    networks:
      - flask

networks:
  flask:
    driver: bridge

volumes:
  dbdata: